name: 'Script'
description: 'Calls a script'
inputs:
  name:
    required: true
    description: "Name to echo"
    default: ""
runs:
  using: "composite"
  steps:
    - run: |
        ls -lah
        ./.github/script/run.sh "${{ inputs.name }}"
      shell: bash
