on:
  workflow_call: {}
  workflow_dispatch: {}
  push: {}

jobs:
  print:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - "Test 1"
          - "Test 2"
          - "Test 3"
          - "Test 4"
    steps:
      - name: "Test workflow"
        with:
          name: ${{ matrix.name }}
        run: echo "${name}"
