on:
  workflow_call: {}
  workflow_dispatch: {}
  push: {}

jobs:
  print:
    strategy:
      matrix:
        name:
          - "Test 1"
          - "Test 2"
          - "Test 3"
          - "Test 4"
    runs-on: ubuntu-latest
    steps:
      - name: "Test workflow"
        run: echo  ${{ matrix.name }}
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Test reusable workflow"
        with:
          name: ${{ matrix.name }}
        uses: ./.github/workflows/echo.yaml

  reusable-print:
    strategy:
      matrix:
        name:
          - "Test 1"
          - "Test 2"
          - "Test 3"
          - "Test 4"
    uses: ./.github/workflows/echo.yaml
    with:
      name: ${{ matrix.name }}