on:
  workflow_call: {}
  workflow_dispatch: {}
  push: {}

jobs:
  print:
    strategy:
      matrix:
        name:
          - "Test 1"
          - "Test 2"
          - "Test 3"
          - "Test 4"
    runs-on: ubuntu-latest
    steps:
      - name: "Test workflow"
        run: echo  ${{ matrix.name }}
      - name: "Test composite action"
        with:
          name: ${{ matrix.name }}
        uses: ./.github/echo/
